language: php

env:
  global:
    - setup=stable

matrix:
  fast_finish: true
  include:
    -   php: 7.2

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --no-interaction
  - composer dump-autoload
